#scons

#Setup our environment, use the extra file
env=Environment()
env['myflag'] = ARGUMENTS.get('flag', 0)	#If not present it defaults to zero
env.Append(CCFLAGS = '-DMYFLAG=$myflag')

#Create the files
env.Object(target = "main.o", source = "main.c")
env.Program(target = "main", source = "main.o")
